apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: my-sa-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: nginx-deployment-test
  labels:
    app: deployment-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: my-sa-test
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80