apiVersion: batch/v1
kind: Job
metadata:
  name: job-test
  namespace: default
spec:
  manualSelector: true
  selector:
    matchLabels:
      job: pi
  template:
    metadata:
      labels:
        job: pi
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4