apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
  namespace: default
  labels:
    type: local
spec:
  manualSelector: true
  selector:
    matchLabels:
      job: pi
  template:
    metadata:
      labels:
        job: pi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests: 
      storage: 500Mi